name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download Source
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Pre-build
      run: |
        dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish Artifact
      run: dotnet publish -c Release -o WebApp 
      
    - name: Upload Artifact
    - uses: actions/upload-artifact@v2.1.3
      with:
        name: WebApp
        path: ./WebApp
